(SELECT DISTINCT
           a.FIELDVALUE AS STUDENT_CLASSIFICATION_CD,
           a.XLATLONGNAME AS STUDENT_CLASSIFICATION_DESC,
           '' AS STUDENT_CLASS_DEF
      FROM ps_rpt.PSXLATITEM a
     WHERE 1 = 1 AND a.FIELDNAME = 'ACADEMIC_LEVEL')