SELECT sg."STUDENT_ID",
           sg."FIRST_NAME",
           sg."MIDDLE_NAME",
           sg."LAST_NAME",
           sg."BIRTH_DT",
           sg."GENDER",
           sg."PRONOUNS",
           sg."EMAIL_ID",
           sg."ETHNICITY_CD",
           sg."DECEASED_IND",
           sg."FIELD10",
           sg."INTERNATIONAL_IND",
           sg."COUNTRY_CD",
           sg."INST_FIRST_TERM",
           sg."HS_NAME",
           sg."HS_CITY",
           sg."HS_STATE",
           sg."HS_SIZE",
           sg."HS_PERCENTILE",
           sg."HS_RANK",
           sg."HS_GPA",
           sg."FIELD21",
           sg."HOME_PHONE",
           sg."FIELD23",
           sg."MOBILE_PHONE",
           sg."MAIL_ADDRESS_1",
           sg."MAIL_ADDRESS2",
           sg."MAIL_CITY",
           sg."MAIL_STATE",
           sg."MAIL_ZIP_CODE",
           sg."FIELD30",
           sg."FIELD31",
           sg."STUDENT_LEGACY_CD",
           sg."STUDENT_ADMIT_CD",
           sg."TRANSFER_STUDENT_IND",
           sg."TRANSFER_INST_CD",
           sg."VETERAN_IND",
           sg."READMIT_IND",
           sg."FIRST_GEN_IND",
           sg."HS_ZIP_CODE",
           sg."ADMISSION_ZIP_CODE",
           sg."REGION_CD",
           sg."ACTIVE_IND",
           sg."USERNAME"
      FROM cmp_population_current_v  hp
           INNER JOIN cmp_student_general_v sg
               ON hp.emplid = sg.student_id