SELECT DISTINCT
            a.FIELDVALUE AS COURSE_REGISTRATION_CD,
            a.XLATLONGNAME AS COURSE_REGISTRATION_DESC
       FROM ps_rpt.PSXLATITEM a
      WHERE 1 = 1 AND a.FIELDNAME = 'STDNT_ENRL_STATUS'
   ORDER BY 1