SELECT DISTINCT ACAD_ORG AS DEPARTMENT_CD, DESCRFORMAL AS NAME
        FROM PS_ACAD_ORG_TBL ACAD_O
       WHERE     EFFDT = (SELECT MAX (EFFDT)
                            FROM PS_ACAD_ORG_TBL
                           WHERE ACAD_O.ACAD_ORG = ACAD_ORG)
             AND EFF_STATUS = 'A'
    ORDER BY ACAD_ORG ASC